version: '3.8'
services:
  boss:
    image: 
    container_name: sasboss-rtd
    network_mode: host
    restart: always
    volumes:
      - ./configuration:/opt/sas/viya/config/etc/boss # Mount your configuration
    environment:
      - BOSS_CONTEXT_FILE=spring/activemq.xml